name: LotW Tool Pull Request
on:
  pull_request:
    branches: [ "master", "msx1", "msx2" ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-net:
    name: LotW Tool PR .NET
    runs-on: windows-2019
    steps:
      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Build
        run: msbuild lotwtool.sln -t:rebuild -property:Configuration=Release -property:Platform="Any CPU"
      - name: Prepare Artifact
        shell: pwsh
        run: |
          mkdir artifact
          cp bin/Release/*.exe artifact
          cp readme.txt artifact
          echo "BUILD_TAG=$(git log -1 --format="%ad--%h" --date=format-local:"%Y-%m-%d-%H%M%S")" >> $env:GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lotwtool-pr--${{ env.BUILD_TAG }}
          path: artifact/
